run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # unchecked errors
    - gosimple      # simplify code
    - govet         # standard go vet
    - ineffassign   # unused assignments
    - staticcheck   # advanced checks
    - unused        # unused code
    - goimports     # import formatting
    - misspell      # spelling mistakes
    - revive        # golint replacement
    - gosec         # security issues (important for web apps)
    - bodyclose     # HTTP response body close
    - errname       # error naming conventions
    - errorlint     # error wrapping

linters-settings:
  goimports:
    local-prefixes: github.com/akitorahayashi/ec-tmpl

  revive:
    rules:
      - name: exported
        disabled: true  # don't require comments on all exports

  gosec:
    excludes:
      - G104  # allow unchecked errors in some cases (overlap with errcheck)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
